-- BlueSpeak: gamification v1 foundation
-- Apply in Supabase SQL editor after billing.sql and usage.sql.
--
-- Design goals:
-- 1) Works with any backend auth type (Supabase JWT, shared JWT, static token)
-- 2) Tracks XP/level/streak + daily progress + event stream
-- 3) Service-role write path (via backend), optional read path for diagnostics

create table if not exists public.gamification_profiles (
  principal_key text primary key,
  plan text not null default 'free' check (plan in ('free', 'pro', 'team', 'enterprise')),
  xp bigint not null default 0 check (xp >= 0),
  level integer not null default 1 check (level >= 1),
  streak_days integer not null default 0 check (streak_days >= 0),
  longest_streak_days integer not null default 0 check (longest_streak_days >= 0),
  coins integer not null default 0 check (coins >= 0),
  last_activity_day date,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists gamification_profiles_plan_idx
  on public.gamification_profiles(plan);

create index if not exists gamification_profiles_updated_at_idx
  on public.gamification_profiles(updated_at desc);

create table if not exists public.gamification_daily_progress (
  day_key date not null,
  principal_key text not null,
  plan text not null default 'free' check (plan in ('free', 'pro', 'team', 'enterprise')),
  words_count integer not null default 0 check (words_count >= 0),
  dictate_count integer not null default 0 check (dictate_count >= 0),
  translate_count integer not null default 0 check (translate_count >= 0),
  rewrite_count integer not null default 0 check (rewrite_count >= 0),
  challenges_completed integer not null default 0 check (challenges_completed >= 0),
  xp_earned integer not null default 0 check (xp_earned >= 0),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  primary key (day_key, principal_key)
);

create index if not exists gamification_daily_progress_day_idx
  on public.gamification_daily_progress(day_key desc);

create index if not exists gamification_daily_progress_plan_idx
  on public.gamification_daily_progress(day_key desc, plan);

create table if not exists public.gamification_events (
  event_id bigint generated by default as identity primary key,
  principal_key text not null,
  day_key date not null default (timezone('utc'::text, now())::date),
  plan text not null default 'free' check (plan in ('free', 'pro', 'team', 'enterprise')),
  event_type text not null check (event_type in ('dictate', 'translate', 'rewrite', 'challenge_complete', 'streak_bonus', 'manual_adjustment')),
  words_count integer not null default 0 check (words_count >= 0),
  xp_delta integer not null default 0,
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists gamification_events_principal_created_idx
  on public.gamification_events(principal_key, created_at desc);

create index if not exists gamification_events_day_idx
  on public.gamification_events(day_key desc);

create index if not exists gamification_events_type_idx
  on public.gamification_events(event_type, created_at desc);

alter table public.gamification_profiles enable row level security;
alter table public.gamification_daily_progress enable row level security;
alter table public.gamification_events enable row level security;

drop policy if exists "Service role can read gamification profiles" on public.gamification_profiles;
create policy "Service role can read gamification profiles"
  on public.gamification_profiles
  for select
  using (auth.role() = 'service_role');

drop policy if exists "Service role can insert gamification profiles" on public.gamification_profiles;
create policy "Service role can insert gamification profiles"
  on public.gamification_profiles
  for insert
  with check (auth.role() = 'service_role');

drop policy if exists "Service role can update gamification profiles" on public.gamification_profiles;
create policy "Service role can update gamification profiles"
  on public.gamification_profiles
  for update
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "Service role can delete gamification profiles" on public.gamification_profiles;
create policy "Service role can delete gamification profiles"
  on public.gamification_profiles
  for delete
  using (auth.role() = 'service_role');

drop policy if exists "Service role can read gamification daily progress" on public.gamification_daily_progress;
create policy "Service role can read gamification daily progress"
  on public.gamification_daily_progress
  for select
  using (auth.role() = 'service_role');

drop policy if exists "Service role can insert gamification daily progress" on public.gamification_daily_progress;
create policy "Service role can insert gamification daily progress"
  on public.gamification_daily_progress
  for insert
  with check (auth.role() = 'service_role');

drop policy if exists "Service role can update gamification daily progress" on public.gamification_daily_progress;
create policy "Service role can update gamification daily progress"
  on public.gamification_daily_progress
  for update
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "Service role can delete gamification daily progress" on public.gamification_daily_progress;
create policy "Service role can delete gamification daily progress"
  on public.gamification_daily_progress
  for delete
  using (auth.role() = 'service_role');

drop policy if exists "Service role can read gamification events" on public.gamification_events;
create policy "Service role can read gamification events"
  on public.gamification_events
  for select
  using (auth.role() = 'service_role');

drop policy if exists "Service role can insert gamification events" on public.gamification_events;
create policy "Service role can insert gamification events"
  on public.gamification_events
  for insert
  with check (auth.role() = 'service_role');

drop policy if exists "Service role can update gamification events" on public.gamification_events;
create policy "Service role can update gamification events"
  on public.gamification_events
  for update
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "Service role can delete gamification events" on public.gamification_events;
create policy "Service role can delete gamification events"
  on public.gamification_events
  for delete
  using (auth.role() = 'service_role');

create or replace function public.gamification_level_for_xp(total_xp bigint)
returns integer
language sql
immutable
as $$
  select greatest(1, floor(sqrt(greatest(total_xp, 0)::numeric / 120.0) + 1)::integer);
$$;

create or replace function public.gamification_record_event(
  p_principal_key text,
  p_plan text,
  p_event_type text,
  p_words_count integer default 0,
  p_xp_delta integer default 0,
  p_source text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  principal_key text,
  xp bigint,
  level integer,
  streak_days integer,
  longest_streak_days integer,
  coins integer,
  last_activity_day date,
  day_key date,
  day_words_count integer,
  day_xp_earned integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_day_key date := timezone('utc'::text, now())::date;
  v_prev_last_day date;
  v_prev_streak integer;
  v_prev_longest integer;
  v_prev_xp bigint;
  v_new_streak integer;
  v_new_longest integer;
  v_new_xp bigint;
  v_new_level integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'forbidden';
  end if;

  if p_principal_key is null or length(trim(p_principal_key)) = 0 then
    raise exception 'principal_key is required';
  end if;

  if p_plan is null or p_plan not in ('free', 'pro', 'team', 'enterprise') then
    p_plan := 'free';
  end if;

  if p_event_type is null or p_event_type not in ('dictate', 'translate', 'rewrite', 'challenge_complete', 'streak_bonus', 'manual_adjustment') then
    raise exception 'invalid event_type';
  end if;

  p_words_count := greatest(coalesce(p_words_count, 0), 0);
  p_xp_delta := coalesce(p_xp_delta, 0);

  insert into public.gamification_events (
    principal_key, day_key, plan, event_type, words_count, xp_delta, source, metadata
  ) values (
    trim(p_principal_key),
    v_day_key,
    p_plan,
    p_event_type,
    p_words_count,
    p_xp_delta,
    p_source,
    coalesce(p_metadata, '{}'::jsonb)
  );

  insert into public.gamification_daily_progress (
    day_key, principal_key, plan, words_count, dictate_count, translate_count, rewrite_count, challenges_completed, xp_earned
  ) values (
    v_day_key,
    trim(p_principal_key),
    p_plan,
    p_words_count,
    case when p_event_type = 'dictate' then 1 else 0 end,
    case when p_event_type = 'translate' then 1 else 0 end,
    case when p_event_type = 'rewrite' then 1 else 0 end,
    case when p_event_type = 'challenge_complete' then 1 else 0 end,
    greatest(p_xp_delta, 0)
  )
  on conflict (day_key, principal_key)
  do update set
    plan = excluded.plan,
    words_count = public.gamification_daily_progress.words_count + excluded.words_count,
    dictate_count = public.gamification_daily_progress.dictate_count + excluded.dictate_count,
    translate_count = public.gamification_daily_progress.translate_count + excluded.translate_count,
    rewrite_count = public.gamification_daily_progress.rewrite_count + excluded.rewrite_count,
    challenges_completed = public.gamification_daily_progress.challenges_completed + excluded.challenges_completed,
    xp_earned = public.gamification_daily_progress.xp_earned + excluded.xp_earned,
    updated_at = timezone('utc'::text, now());

  insert into public.gamification_profiles (principal_key, plan)
  values (trim(p_principal_key), p_plan)
  on conflict (principal_key) do nothing;

  select
    gp.last_activity_day,
    gp.streak_days,
    gp.longest_streak_days,
    gp.xp
  into
    v_prev_last_day,
    v_prev_streak,
    v_prev_longest,
    v_prev_xp
  from public.gamification_profiles gp
  where gp.principal_key = trim(p_principal_key)
  for update;

  if v_prev_last_day is null then
    v_new_streak := 1;
  elsif v_prev_last_day = v_day_key then
    v_new_streak := coalesce(v_prev_streak, 0);
  elsif v_prev_last_day = v_day_key - 1 then
    v_new_streak := coalesce(v_prev_streak, 0) + 1;
  else
    v_new_streak := 1;
  end if;

  v_new_longest := greatest(coalesce(v_prev_longest, 0), v_new_streak);
  v_new_xp := greatest(0, coalesce(v_prev_xp, 0) + p_xp_delta);
  v_new_level := public.gamification_level_for_xp(v_new_xp);

  update public.gamification_profiles
     set plan = p_plan,
         xp = v_new_xp,
         level = v_new_level,
         streak_days = v_new_streak,
         longest_streak_days = v_new_longest,
         last_activity_day = v_day_key,
         updated_at = timezone('utc'::text, now())
   where principal_key = trim(p_principal_key);

  return query
  select
    gp.principal_key,
    gp.xp,
    gp.level,
    gp.streak_days,
    gp.longest_streak_days,
    gp.coins,
    gp.last_activity_day,
    dp.day_key,
    dp.words_count,
    dp.xp_earned
  from public.gamification_profiles gp
  left join public.gamification_daily_progress dp
    on dp.principal_key = gp.principal_key
   and dp.day_key = v_day_key
  where gp.principal_key = trim(p_principal_key);
end;
$$;

grant execute on function public.gamification_level_for_xp(bigint) to authenticated, anon, service_role;
grant execute on function public.gamification_record_event(text, text, text, integer, integer, text, jsonb) to service_role;
revoke execute on function public.gamification_record_event(text, text, text, integer, integer, text, jsonb) from authenticated, anon, public;

